# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_content_type_id', models.PositiveIntegerField(db_index=True)),
                ('owner_object_id', models.PositiveIntegerField(db_index=True)),
                ('co_owner_content_type_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('co_owner_object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('key', models.CharField(db_index=True, help_text=b'Key the KeyValue', max_length=50)),
                ('value', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='keyvalue',
            unique_together=set([('owner_content_type_id', 'owner_object_id', 'co_owner_content_type_id', 'co_owner_object_id', 'key')]),
        ),
    ]
